var fs = require('fs');
var lines = [];
lines.push("const state = { user: null, token: null, currentTab: 'dashboard', navHistory: [], customers: [], leads: [], opportunities: [], orders: [], complaints: [], visits: [], accounts: [], targets: [], dashboardData: null, financial: null, fsComponents: [], monthlyData: [], topGL: [], transactions: [] };");
lines.push("const API = '';");
lines.push("const ROLE_HIERARCHY = { super_admin: ['dashboard','customers','leads','opportunities','orders','complaints','visits','team','reports','accounts','financials'], admin: ['dashboard','customers','leads','opportunities','orders','complaints','visits','team','reports','accounts','financials'], sales_head: ['dashboard','customers','leads','opportunities','orders','visits','team','reports'], so: ['dashboard','customers','leads','opportunities','orders','visits'], contact_center: ['complaints'], sales_excellence: ['reports','financials'], management: ['dashboard','reports','financials'] };");
lines.push("const NAV_GROUPS = { main: { title: 'Main', items: [{ id: 'dashboard', label: 'Dashboard' }] }, modules: { title: 'CRM Modules', items: [{ id: 'customers', label: 'Customers' },{ id: 'leads', label: 'Leads' },{ id: 'opportunities', label: 'Opportunities' },{ id: 'orders', label: 'Orders' },{ id: 'complaints', label: 'Complaints' },{ id: 'visits', label: 'Visits' }] }, operations: { title: 'Operations', items: [{ id: 'team', label: 'Team' },{ id: 'reports', label: 'Reports' },{ id: 'accounts', label: 'Accounts' }] }, analytics: { title: 'Analytics', items: [{ id: 'financials', label: 'Financials' }] } };");
lines.push("const NAV_ICONS = { dashboard: '\uD83D\uDCCA', customers: '\uD83D\uDC65', leads: '\uD83C\uDFAF', opportunities: '\uD83D\uDCB0', orders: '\uD83D\uDED2', complaints: '\uD83D\uDEE0\uFE0F', visits: '\uD83D\uDCCD', team: '\uD83D\uDC65', reports: '\uD83D\uDCCA', accounts: '\u2699\uFE0F', financials: '\uD83D\uDCB5' };");
console.log("Part 1 written: " + lines.length + " lines");
fs.writeFileSync(__dirname + "/app-temp.txt", lines.join("\n"));
